@host=http://localhost:5147

GET {{host}}/tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYjcxODI4Ny02ZmE4LTQ4N2QtYTVlMC0xNjkzMWFjZWVlMjMiLCJnaXZlbl9uYW1lIjoiTWF4IiwiZmFtaWx5X25hbWUiOiJTZXZlcm92IiwianRpIjoiZWEyMzA2ODMtYjAzMi00NWRjLWJmODMtOGE0ZmE1YmIyMGJmIiwiZXhwIjoxNzEzNjM1ODY5LCJpc3MiOiJUZXN0c0J1aWxkZXIiLCJhdWQiOiJUZXN0c0J1aWxkZXIifQ.BnxQp6X4HNy24DncQWpJcGBHwwGllt1H_2FZ8Wwuhuw