@host=https://3ca0-185-128-201-41.ngrok-free.app

GET {{host}}/tests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZjQ1M2Q5Ni0zMWI0LTRlNzAtYTlmOC1iZTdlYzQ4NzVmMWQiLCJnaXZlbl9uYW1lIjoiTWF4IiwiZmFtaWx5X25hbWUiOiJTZXZlcm92IiwianRpIjoiNjFjYzBhOTUtYzdmMi00ZmIwLThjNDEtMThjNzgyYjQ3YjkwIiwiZXhwIjoxNzE3NTQwNTYzLCJpc3MiOiJUZXN0c0J1aWxkZXJEQiIsImF1ZCI6IlRlc3RzQnVpbGRlckRCIn0.YfcYEqhDyrNy2Yu3KgS7Svw33otBB1ml5eeg17PoQf0
