@host=https://3ca0-185-128-201-41.ngrok-free.app
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Max",
    "lastName": "Severov",
    "email": "pupajupa@mail.ru",
    "password": "max1234"
} 